version: '3'
services:
  front:
    image: virtualvinodh/aksharamukha-front
    ports:
      - "12345:80"
  back:
    image: virtualvinodh/aksharamukha-back
    ports:
      - "8085:8085"
  fonts:
    image: virtualvinodh/aksharamukha-fonts
    ports:
      - "9899:80"